language: ruby
cache: bundler
rvm: 2.3.1
branches:
  only:
  -  master
addons:
  ssh_known_hosts: git.wpengine.com
script:
- cd wp-content/themes/nuclearnetwork
- compass compile
before_install:
- openssl aes-256-cbc -K $encrypted_b2b52edfc1db_key -iv $encrypted_b2b52edfc1db_iv
  -in nuclearnetwork_rsa.enc -out /tmp/nuclearnetwork_travis -d
- gem install compass
before_deploy:
- cd $TRAVIS_BUILD_DIR
deploy:
- provider: script
  skip_cleanup: true
  script: chmod +x deploy.sh && sh deploy.sh
  on:
    branch: master